site_name: ECCTY Seminar - Dallas
nav:
  - Home: index.md
  - Day 1 Labs: day1.md
  - Lab environments: 
    - Liberty & App Mod Lab environment assignments: liberty-lab-env-assignments.md
    - Containers & OpenShift Lab environment assignments: containers-lab-env-assignments.md
    - WebSphere Automation Lab environment assignments: WSA-lab-env-assignments.md
  - Day 2 - Business Automation: day2.md  
theme: readthedocs  
extra_css: ["extra.css"]
